### ISSUE TITLE
An hour timestamp only checks once per hour

### ISSUE THREAD

**Issue by seiyria** [ihym/ngx-timeago#24]
## Current behavior

If I create a timestamp for exactly an hour, the live timeago tick does not fire for an hour, meaning the live updating is not really correct.

## Expected behavior
It should probably tick more frequently than every hour if the time is between an hour and a day.

## How do you think that we should fix this?
Probably, tick every 5 minutes instead of every hour - that way when it gets into range it will start ticking at a reasonable pace.

## Minimal reproduction of the problem with instructions
controller.timestamp = Date.now() + 1000 * 60 * 60;
{{ timestamp | timeago }}

## Environment

<pre><code>
ngx-timeago version: ^1.0.0
Angular version: 6.0.4

Browser:
- all
</code></pre>

**Comment by ihym** [comment]
Hmm, I'll check it.
Fyi this is related to [clock's](https://github.com/ihym/ngx-timeago/blob/master/lib/src/timeago.clock.ts) implementation. So, in the meantime, you can provide your own implementation to make this work.

**Comment by seiyria** [comment]
My workaround was just to make the timer 59:59:9999 instead of 60:00:00.

**Comment by ihym** [comment]
@seiyria i cant repro. Maybe it's fixed by https://github.com/ihym/ngx-timeago/commit/afe3679d5461740cac9594eddd803da226315b40. Is this still an issue?
