### ISSUE TITLE
Output is incorrect

### ISSUE THREAD

**Issue by mikev10** [ihym/ngx-timeago#33]
When I enter this pipe `{{1549817400 | timeago:live}}` it says it was 49 years ago which is incorrect. Can you let me know why it is being outputted this way and how to correct this? It should be 2 days ago.

**Comment by ihym** [comment]
You should pass a value in one of [those](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Syntax) formats.
For your case, I guess you should pass `1549817400000`.

**Comment by mikev10** [comment]
But your documentation says it's for a timestamp and when I use your pipe example `<div>{{2671200000 | timeago:live}}</div>` it also says 49 years ago. So does it not allow for me to pass a Unix Time Stamp? How did you come up with the timestamp above?

**Comment by ihym** [comment]
Hmm I don't remember why I chose this :)
I guess the documentation needs to be more precise.
In any case, your input will be [fed](https://github.com/ihym/ngx-timeago/blob/master/lib/src/util.ts#L9) in a Date object, so it's format should be the expected one..

**Comment by saintaze** [comment]
has this been rectified? I am facing the same issue
