### ISSUE TITLE
Cannot set property 'strings' of undefined

### ISSUE THREAD

**Issue by Smoodys** [ihym/ngx-timeago#34]
I got this error "Cannot set property 'strings' of undefined" when i change the language format on my contructor

`import { TimeagoIntl } from 'ngx-timeago';`
`import { strings as englishShortStrings } from 'ngx-timeago/language-strings/en-short';
`
`constructor(intl: TimeagoIntl) {`
`intl.strings = englishShortStrings;`
`intl.changes.next();`
`  }`

If anyone know how to fix this problem please help!
Cordialy

**Comment by ihym** [comment]
You have to provide the intl service.
[Here](https://github.com/ihym/ngx-timeago/blob/master/demo/app/child/child.module.ts#L23) is an example.

**Comment by Smoodys** [comment]
![image](https://user-images.githubusercontent.com/36553449/53433135-24941a00-39f4-11e9-931a-726ad8ebe4f9.png)
 I provided it, still the same error

**Comment by ihym** [comment]
So whats the value of TimeagoIntl? You don't provide any in this snippet..

**Comment by ihym** [comment]
Write `intl: TimeagoIntl`

**Comment by Smoodys** [comment]
Thank you for your help and your time, problem solved!
