### ISSUE TITLE
Docs claim format is the only required method on the custom formatter

### ISSUE THREAD

**Issue by arturhun** [ihym/ngx-timeago#35]
## Current behavior

Readme states as follows:

```
Write your own formatter
If you want to write your own formatter, you need to create a class that implements TimeagoFormatter. The only required method is format that must return the final string.
``` 

## Expected behavior

The above is not true, TS requires also `parse` method to be extended.

## Minimal reproduction of the problem with instructions
Try not to provide `parse` in your custom formatter.
https://stackblitz.com/edit/angular-7avyzw?file=src%2Fapp%2Fapp.module.ts

## Environment

<pre><code>
ngx-timeago version: 1.0.0
Angular version: 7.x
</code></pre>

I would suggest to either make the `parse` method indeed not required, or export the internal default one.

**Comment by ihym** [comment]
https://github.com/ihym/ngx-timeago/commit/52b45dc9d6f74c309ed0814f974a37dbbc6d1f6e
