### ISSUE TITLE
angular 6.1.10

### ISSUE THREAD

**Issue by mikila85** [ihym/ngx-timeago#36]
## Current behavior
`Uncaught Error: Template parse errors:
The pipe 'timeago' could not be found`

## Expected behavior
Should work after import

## Minimal reproduction of the problem with instructions
`npm install ngx-timeago --save`
..then add:
```
import {TimeagoModule} from "ngx-timeago";
@NgModule({
imports: [
    TimeagoModule.forRoot()
```
then try use in code.

## Environment

<pre><code>
ngx-timeago version: ^1.0.1
Angular version: 6.1.10
</code></pre>

**Comment by mikila85** [comment]
my bad,
wrong placement of import.

**Comment by yassern** [comment]
hello friend, how u resolved that?
