### ISSUE TITLE
Pipe Internationalization not working

### ISSUE THREAD

**Issue by TekSiDoT** [ihym/ngx-timeago#38]
## Current behavior
Internationalization does not work

## Expected behavior
Internationalization does work :)

## Minimal reproduction of the problem with instructions
* Follow the Readme to setup Internationalization 
* ... String will still show up as English

Reproduction at https://stackblitz.com/edit/angular-6hhf8a

## Environment
ngx-timeago version: 1.0.2
Angular version: 6.0.0, 8.0.0, 8.2.2

Browser:
- all

**Comment by ihym** [comment]
You should provide a custom formatter as the default doesn't provide language support.
You can use TimeagoCustomFormatter or you can write your own :)
Check https://github.com/ihym/ngx-timeago#i18n for  the exact setup.

**Comment by TekSiDoT** [comment]
Perfect, thanks!

**Comment by dalepo** [comment]
I have the same issue with angular 9
I slightly edited OP's stackblitz link to see if it was working

https://stackblitz.com/edit/angular-no8wuu
```
@Injectable()
class MySpanishFormat extends TimeagoIntl {
  strings = spanishStrings;
  constructor() {
    super();
    this.strings = spanishStrings;
    console.log(this.strings);
    console.log('WOrks?');
  }
}

@NgModule({
  imports:      [ BrowserModule, FormsModule, TimeagoModule.forRoot({
    intl: { provide: TimeagoIntl, useClass: MySpanishFormat }
  })
 ],
  providers: [TimeagoIntl],
  declarations: [ AppComponent, HelloComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }


```

Output: 

3 minutes ago
3 minutes ago

It should use the spanish strings right? Or am I doing something wrong?
