### ISSUE TITLE
transform method in timeago.pipe.ts should take an "any" instead of a "number" as input type

### ISSUE THREAD

**Issue by sammeel** [ihym/ngx-timeago#39]
## Current behavior

When creating an Angular library with a component using ngx-timeago, then compiling this project fails due to the fact that our model uses a Date type instead of a number.
Where normal usage (passing a string, a date or a number) works fine when you use ngx-timeago immediately in your project, it does not work when using an angular library. It seems that the type checking is more strict compared to normal usage (even with --aot)

ngx-timeago is added to the module and also exported from the module.

simplified model:
`export class Model {
  lastModified: Date;
}`

Html:
`<p class="modified">{{ item.lastModified | timeago }}</p>`

The above code gives the following exception when running ng-packagr:

Building Angular Package
Building entry point ''
Compiling TypeScript sources through ngc
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

BUILD ERROR
projects\shared-lib\src\lib\components\my-component\my-component.component.html(24,68): : Argument of type 'string | Date' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.

Error: projects\shared-lib\src\lib\components\my-component\my-component.component.html(24,68): : Argument of type 'string | Date' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.

    at Object.<anonymous> (C:\_src\Shared\node_modules\ng-packagr\lib\ngc\compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at C:\_src\Shared\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\_src\Shared\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\_src\Shared\node_modules\ng-packagr\lib\ngc\compile-source-files.js:17:12)
    at Object.<anonymous> (C:\_src\Shared\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at C:\_src\Shared\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

## Expected behavior
The compilation should succeed when passing valid values from Date type and string.

## How do you think that we should fix this?
The timeago pipe should take in an object of type "number | date | string" since it parses all of those to a date, or it could even be an any since it tries to parse anything to a date anyway.

## Minimal reproduction of the problem with instructions

Steps to reproduce:
1. Create an angular library project
2. Add ngx-timeago to the project and export is
3. Add a component to the project and export it
4. Build the library project ==> error occurs

## Environment

<pre><code>
ngx-timeago version: 1.0.3
Angular version: 7.2.0

Browser: no browser, during compilation

For Tooling issues:
- Node version: 10.18.0 XX 
- Platform:  Windows

Others:
</code></pre>

**Comment by ihym** [comment]
0fd67e637a8dc6a441469d2dc4fb15531c330d5b
Try with latest version (1.0.4)

**Comment by sammeel** [comment]
Works perfectly, thanks for the quick response.
