### ISSUE TITLE
:live not required

### ISSUE THREAD

**Issue by TDroogers** [ihym/ngx-timeago#51]
Hi,

I like this package, but it looks like the readme is wrong/outdated. 
When adding the component like this: `{{lastUpdate | timeago:live}}` it works on my local machine.
However docker.com failed with the following error: 

> Property 'live' does not exist on type 'ButtonComponent'

After removing the :live `{{lastUpdate | timeago}}` it still worked and time increased as expected.
Is this behaviour changed? Or am I missing something?

**Comment by ihym** [comment]
Make sure that `live` exists.
