### ISSUE TITLE
Live off shows 'x seconds ago', good to show 'few seconds ago'

### ISSUE THREAD

**Issue by sathiyad** [ihym/ngx-timeago#56]
Using `timeago:false` shows `x seconds ago` it's good to show `a few seconds ago`.

![Screenshot from 2022-07-18 12-34-17](https://user-images.githubusercontent.com/25609136/179459878-9a4792bc-c4c3-4de3-aaa4-f13dedb52854.png)

**Comment by ihym** [comment]
You can customize everything using your own formatter and/or custom strings
