### ISSUE TITLE
Incompatibility with Angular 16

### ISSUE THREAD

**Issue by AmitMY** [ihym/ngx-timeago#59]
## Current behavior
> Error: Unexpected value 'TimeagoModule' imported by the module 'AppModule'. Please add an @NgModule annotation.

## Expected behavior
Should work

## How do you think that we should fix this?
add @NgModule

**Comment by Maransatto** [comment]
ngcc has been removed from Angular v16

https://angular.io/guide/update-to-version-16#angular-compatibility-compiler-ngcc-has-been-removed

**Comment by ihym** [comment]
PRs are welcome

**Comment by cyrillbrito** [comment]
I opened a PR with the upgrade to angular 16 and to enable ivy.
There is one thing that still needs to be done, the `language-strings` are not being included in the built files.
The previous strategy was using gulp to do this, but I suspect there is some way to achieve without it, but I was not able to find it :( 

Can someone help?
