### ISSUE TITLE
Production build breaks internationalization strings

### ISSUE THREAD

**Issue by kreatemore** [ihym/ngx-timeago#9]
**Expected behaviour**

When doing `ng build --prod` with the custom formatter times show up as `less than a minute ago`

**Actual behaviour**

Instead of `less than a minute ago` it shows `n second` and instead of `n minutes ago` shows `n minute`

Component:

```
  constructor(private store: AngularFirestore, private intl: TimeagoIntl) {}

  ngOnInit(): void {
    // This is to hide a warning until a new version of Firebase package comes
    this.store.firestore.settings({timestampsInSnapshots: true});

    this.setClockInternationalization();
    this.fetchResources();
  }

  private setClockInternationalization(): void {
    this.intl.strings = englishStrings;
    this.intl.changes.next();
  }
```

Module:

```
@NgModule({
  imports: [
    AngularFirestoreModule,
    AvatarModule,
    CommonModule,
    MatButtonModule,
    MatProgressBarModule,
    MatTableModule,
    TimeagoModule.forRoot({
      clock: {provide: TimeagoClock, useClass: SlowUpdatingClock},
      formatter: {provide: TimeagoFormatter, useClass: TimeagoCustomFormatter},
    }),
  ],
  providers: [TimeagoIntl],
})
```

I'm sure it's an easy fix, great work though!

**Comment by ihym** [comment]
You forgot to provide TimeagoIntl in your forRoot config.
Check https://github.com/ihym/ngx-timeago/blob/8e6fb002b9eac1acd1b2650974f886d9ad5ad701/demo/app/child/child.module.ts#L23

**Comment by ihym** [comment]
Hmm now I noticed the providers property..
Weird. Are there any errors? Can you setup a plunker with your issue?

I tried a similar setup in the demo and it worked fine.

**Comment by ihym** [comment]
Thanks, this was an actual issue.

https://github.com/ihym/ngx-timeago/releases/tag/v0.3.1

It should be fixed now.
